export const THAY_DOI_INPUT = "THAY_DOI_INPUT";
export const THEM_SINH_VIEN = "THEM_SINH_VIEN";
export const XOA_SINH_VIEN = "XOA_SINH_VIEN";
export const CHINH_SUA_SINH_VIEN = "CHINH_SUA_SINH_VIEN";
export const CAP_NHAT_SINH_VIEN = "CAP_NHAT_SINH_VIEN";
export const THAY_DOI_TIM_KIEM = "THAY_DOI_TIM_KIEM";
export const TIM_KIEM_SINH_VIEN = "TIM_KIEM_SINH_VIEN";